CREATE DATABASE IF NOT EXISTS IDS;
use IDS;

CREATE TABLE IF NOT EXISTS usuarios (
  id UUID PRIMARY KEY,
  usuario VARCHAR(25) NOT NULL UNIQUE,
  email VARCHAR(50) NOT NULL UNIQUE,
  contrasena VARCHAR(12) NOT NULL,
  fecha_registro DATETIME DEFAULT CURRENT_TIMESTAMP
);